### ISSUE TITLE
Remove unnecessary word in README

### ISSUE THREAD

**Issue by branbick** [branbick/init-from-input-file#4]
Remove the "then" between "which" and "triggers." It's unnecessary.

https://github.com/branbick/init-from-input-file/blob/a3a5f63e71ccd70ae2f6664fec4ffad4f5517635/README.md#L93

**Comment by Mount-Blanc** [comment]
Hello, I would like to do this issue.

**Comment by branbick** [comment]
Go for it, @Mount-Blanc!
